web_bind:
  address: '0.0.0.0'
  port: 8184

camlytics:
  url: "http://localhost:48462/"

logging:
  file: logs/people-counter.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5